### ISSUE TITLE
Errores de compilación arrojan generan mensajes excesivamente largos

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-ruby-runner#44]
Por ejemplo si en [este ejercicio](https://mumuki.io/central/exercises/3324-programacion-con-objetos-polimorfismo-y-encapsulamiento-pepita-esta-feliz) falta un end: 

```ruby
module Pepita
  @energia = 1000

  def self.energia
    @energia 
  end

  def self.volar_en_circulos!
    @energia -= 10
  end
  
  def self.comer_alpiste!(gramos)
    @energia += gramos * 15
  end  

  def self.debil?
    @energia < 100
  end
  
  def self.feliz?
    @energia > 1000
  end
```

Se obtiene el siguente error: 

```
/usr/local/bundle/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `load': solucion.rb:93: syntax error, unexpected end-of-input, expecting keyword_end (SyntaxError)
	from /usr/local/bundle/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `block in load_spec_files'
	from /usr/local/bundle/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `each'
	from /usr/local/bundle/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `load_spec_files'
	from /usr/local/bundle/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:100:in `setup'
	from /usr/local/bundle/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:86:in `run'
	from /usr/local/bundle/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:71:in `run'
	from /usr/local/bundle/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:45:in `invoke'
	from /usr/local/bundle/gems/rspec-core-3.5.4/exe/rspec:4:in `<top (required)>'
	from /usr/local/bundle/bin/rspec:23:in `load'
	from /usr/local/bundle/bin/rspec:23:in `<main>'
```

Más allá de que sería deseable incorporar un  `FeedbackHook`, el mensaje debería ser recortado, eliminado el strack-trace, y mostrando sólo lo siguiente: 

```ruby
solucion.rb:93: syntax error, unexpected end-of-input, expecting keyword_end (SyntaxError)
```

**Comment by flbulgarelli** [comment]
See https://github.com/mumuki/mumuki-javascript-runner/pull/28
